//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoelPush.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoelPush.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturer une région.
        /// </summary>
        public static string CaptureRegion {
            get {
                return ResourceManager.GetString("CaptureRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturer l’écran.
        /// </summary>
        public static string CaptureScreen {
            get {
                return ResourceManager.GetString("CaptureScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --file.
        /// </summary>
        public static string CommandFileName {
            get {
                return ResourceManager.GetString("CommandFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --noup.
        /// </summary>
        public static string CommandLineNoUp {
            get {
                return ResourceManager.GetString("CommandLineNoUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] crosscustom {
            get {
                object obj = ResourceManager.GetObject("crosscustom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] crosscustom2 {
            get {
                object obj = ResourceManager.GetObject("crosscustom2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter NoelPush.
        /// </summary>
        public static string ExitNoelPush {
            get {
                return ResourceManager.GetString("ExitNoelPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historique.
        /// </summary>
        public static string Historique {
            get {
                return ResourceManager.GetString("Historique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon_upload {
            get {
                object obj = ResourceManager.GetObject("icon_upload", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lien copié dans le presse-papier..
        /// </summary>
        public static string LinkPasted {
            get {
                return ResourceManager.GetString("LinkPasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noelpush.
        /// </summary>
        public static string NamePicture {
            get {
                return ResourceManager.GetString("NamePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream notif {
            get {
                return ResourceManager.GetStream("notif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur durant l’envoi….
        /// </summary>
        public static string PopupConnexionFailed1 {
            get {
                return ResourceManager.GetString("PopupConnexionFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez vérifier votre connexion internet..
        /// </summary>
        public static string PopupConnexionFailed2 {
            get {
                return ResourceManager.GetString("PopupConnexionFailed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image copiée !.
        /// </summary>
        public static string PopupCopy1 {
            get {
                return ResourceManager.GetString("PopupCopy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image copiée dans le presse-papier..
        /// </summary>
        public static string PopupCopy2 {
            get {
                return ResourceManager.GetString("PopupCopy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoelPush vient d’être installé !.
        /// </summary>
        public static string PopupFirstRun1 {
            get {
                return ResourceManager.GetString("PopupFirstRun1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez deux fois sur Impr Écran pour capturer une région. Trois fois pour capturer tout l’écran..
        /// </summary>
        public static string PopupFirstRun2 {
            get {
                return ResourceManager.GetString("PopupFirstRun2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lien de l’historique copié dans le presse-papier !.
        /// </summary>
        public static string PopupHistorique1 {
            get {
                return ResourceManager.GetString("PopupHistorique1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrez-le dans votre navigateur préféré..
        /// </summary>
        public static string PopupHistorique2 {
            get {
                return ResourceManager.GetString("PopupHistorique2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur durant l’envoi….
        /// </summary>
        public static string PopupPictureTooLarge1 {
            get {
                return ResourceManager.GetString("PopupPictureTooLarge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’image était trop volumineuse..
        /// </summary>
        public static string PopupPictureTooLarge2 {
            get {
                return ResourceManager.GetString("PopupPictureTooLarge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image envoyée !.
        /// </summary>
        public static string PopupUpload1 {
            get {
                return ResourceManager.GetString("PopupUpload1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lien copié dans le presse-papier..
        /// </summary>
        public static string PopupUpload2 {
            get {
                return ResourceManager.GetString("PopupUpload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur durant l’envoi….
        /// </summary>
        public static string PopupUploadFailed1 {
            get {
                return ResourceManager.GetString("PopupUploadFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;image n&apos;a pas pu être envoyée..
        /// </summary>
        public static string PopupUploadFailed2 {
            get {
                return ResourceManager.GetString("PopupUploadFailed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoi en cours….
        /// </summary>
        public static string ScreenInProgress {
            get {
                return ResourceManager.GetString("ScreenInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoelPush.
        /// </summary>
        public static string SoftwareName {
            get {
                return ResourceManager.GetString("SoftwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
