//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoelPush.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoelPush.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capturer une région.
        /// </summary>
        public static string CaptureRegion {
            get {
                return ResourceManager.GetString("CaptureRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capturer l’écran.
        /// </summary>
        public static string CaptureScreen {
            get {
                return ResourceManager.GetString("CaptureScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à --file.
        /// </summary>
        public static string CommandFileName {
            get {
                return ResourceManager.GetString("CommandFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à --noup.
        /// </summary>
        public static string CommandLineNoUp {
            get {
                return ResourceManager.GetString("CommandLineNoUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        public static byte[] crosscustom {
            get {
                object obj = ResourceManager.GetObject("crosscustom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        public static byte[] crosscustom2 {
            get {
                object obj = ResourceManager.GetObject("crosscustom2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter NoelPush.
        /// </summary>
        public static string ExitNoelPush {
            get {
                return ResourceManager.GetString("ExitNoelPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique.
        /// </summary>
        public static string Historique {
            get {
                return ResourceManager.GetString("Historique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        public static System.Drawing.Icon icon_upload {
            get {
                object obj = ResourceManager.GetObject("icon_upload", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lien copié dans le presse-papier..
        /// </summary>
        public static string LinkPasted {
            get {
                return ResourceManager.GetString("LinkPasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à noelpush.
        /// </summary>
        public static string NamePicture {
            get {
                return ResourceManager.GetString("NamePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream notif {
            get {
                return ResourceManager.GetStream("notif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur durant l’envoi….
        /// </summary>
        public static string PopupConnexionFailed1 {
            get {
                return ResourceManager.GetString("PopupConnexionFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez vérifier votre connexion internet..
        /// </summary>
        public static string PopupConnexionFailed2 {
            get {
                return ResourceManager.GetString("PopupConnexionFailed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image copiée !.
        /// </summary>
        public static string PopupCopy1 {
            get {
                return ResourceManager.GetString("PopupCopy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image copiée dans le presse-papier..
        /// </summary>
        public static string PopupCopy2 {
            get {
                return ResourceManager.GetString("PopupCopy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NoelPush vient d’être installé !.
        /// </summary>
        public static string PopupFirstRun1 {
            get {
                return ResourceManager.GetString("PopupFirstRun1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyez deux fois sur Impr Écran pour capturer une région. Trois fois pour capturer tout l’écran..
        /// </summary>
        public static string PopupFirstRun2 {
            get {
                return ResourceManager.GetString("PopupFirstRun2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lien de l’historique copié dans le presse-papier !.
        /// </summary>
        public static string PopupHistorique1 {
            get {
                return ResourceManager.GetString("PopupHistorique1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrez-le dans votre navigateur préféré..
        /// </summary>
        public static string PopupHistorique2 {
            get {
                return ResourceManager.GetString("PopupHistorique2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur durant l’envoi….
        /// </summary>
        public static string PopupPictureTooLarge1 {
            get {
                return ResourceManager.GetString("PopupPictureTooLarge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L’image était trop volumineuse..
        /// </summary>
        public static string PopupPictureTooLarge2 {
            get {
                return ResourceManager.GetString("PopupPictureTooLarge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image envoyée !.
        /// </summary>
        public static string PopupUpload1 {
            get {
                return ResourceManager.GetString("PopupUpload1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lien copié dans le presse-papier..
        /// </summary>
        public static string PopupUpload2 {
            get {
                return ResourceManager.GetString("PopupUpload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur durant l’envoi….
        /// </summary>
        public static string PopupUploadFailed1 {
            get {
                return ResourceManager.GetString("PopupUploadFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;image n&apos;a pas pu être envoyée..
        /// </summary>
        public static string PopupUploadFailed2 {
            get {
                return ResourceManager.GetString("PopupUploadFailed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi en cours….
        /// </summary>
        public static string ScreenInProgress {
            get {
                return ResourceManager.GetString("ScreenInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NoelPush.
        /// </summary>
        public static string SoftwareName {
            get {
                return ResourceManager.GetString("SoftwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
